name: invisible_watermark
description: "A Flutter package for making invisible watermarks on images."
version: 0.0.1+1
homepage: "https://github.com/xiehan198712/invisible_watermark"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0